import React from 'react';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { Header } from '@/components/header';
import { Providers } from '@/app/providers';
import { Container } from '@/components/container';
import { ConfirmModal } from '@/components/confirm-modal';
import './globals.css';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin']
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin']
});

export const metadata: Metadata = {
    title: 'Employees',
    description: 'Generated by create next app'
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html lang='en' suppressHydrationWarning>
            <body className='h-screen cursor-default select-none'>
                <Providers>
                    <Container>
                        <Header />
                        { children }
                        <ConfirmModal />
                    </Container>
                </Providers>
            </body>
        </html>
    );
}
